# Generated by Django 5.2 on 2025-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_has_book_access_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_book_access',
            new_name='has_ev_access',
        ),
        migrations.AddField(
            model_name='user',
            name='has_sv_access',
            field=models.BooleanField(default=False),
        ),
    ]
