# Generated by Django 5.2 on 2025-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='path',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
