# Generated by Django 5.2 on 2025-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
